management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.beranda, name='berandapelanggan'),
    path('kategoripelanggan/<int:kategori_id>/', views.kategori_view, name='kategoripelanggan'),
    path('tambah-ke-keranjang/<int:katalog_id>/', views.tambah_ke_keranjang, name='tambah_ke_keranjangpelanggan'),
    path('keranjang/', views.tampil_keranjang, name='keranjangpelanggan'),
    path('update-keranjang/', views.update_keranjang, name='update_keranjangpelanggan'),  # Path untuk update keranjang
    path('update_keranjang_all/', views.update_keranjang_all, name='update_keranjang_all'),

    path('simpan-sewa/', views.simpan_sewa, name='simpan_sewapelanggan'),
    path('pencarianpelanggan/', views.pencarian_view, name='pencarianpelanggan'),
    path('syarat-dan-ketentuan/', views.syarat_dan_ketentuan, name='syarat_dan_ketentuan'),
    path('cara-pemesanan/', views.cara_pemesanan, name='cara_pemesanan'),

    path('registerpelanggan/', views.register_pelanggan, name='registerpelanggan'),
    path('loginpelanggan/', views.login_pelanggan, name='loginpelanggan'),
    # path('history-sewapelanggan/', views.history_sewa, name='history_sewapelanggan'),
    path('history-sewapelanggan/', views.history_sewa, name='history_sewapelanggan'),
    path('generate_midtrans_token/', views.generate_midtrans_token, name='generate_midtrans_token'),
    path('batal-sewa/', views.batal_sewa, name='batal_sewa'),
    path('upload_bukti_pembayaran/', views.upload_bukti_pembayaran, name='upload_bukti_pembayaran'),
    path('get_detail_pembayaran/<int:sewa_id>/', views.get_detail_pembayaran, name='get_detail_pembayaran'),
    path('logoutpelanggan/', views.logout_pelanggan, name='logoutpelanggan'),
    # admin

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sewa_baju/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib import admin
# from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path,include
from management import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_view, name='login'),
    path('home/', views.home, name='home'),
    path('pelanggan/', views.pelanggan, name='pelanggan'),
    path('pelanggan/create/', views.pelanggan_create, name='pelanggan_create'),
    path('pelanggan/update/<int:pk>/', views.pelanggan_update, name='pelanggan_update'),
    path('pelanggan/delete/<int:pk>/', views.pelanggan_delete, name='pelanggan_delete'),
    path('kategori/', views.kategori, name='kategori'),
    path('kategori/create/', views.kategori_create, name='kategori_create'),
    path('kategori/update/<int:pk>/', views.kategori_update, name='kategori_update'),
    path('kategori/delete/<int:pk>/', views.kategori_delete, name='kategori_delete'),
    path('katalog/', views.katalog, name='katalog'),
    path('katalog/create/', views.katalog_create, name='katalog_create'),
    path('katalog/update/<int:pk>/', views.katalog_update, name='katalog_update'),
    path('katalog/delete/<int:pk>/', views.katalog_delete, name='katalog_delete'),
    path('sewa/', views.sewa_list, name='sewa'),
    path('laporansewa/', views.laporansewa_list, name='laporansewa'),
    path('export-sewa-excel/', views.export_sewa_excel, name='export_sewa_excel'),
    path('update_status_bayar/<int:sewa_id>/', views.update_status_bayar, name='update_status_bayar'),
    path('tambah-sewa/', views.tambah_sewa, name='tambah_sewa'),
    path('daftar-sewa/', views.daftar_sewa, name='daftar_sewa'),
    path('users/', views.user_list, name='users'),
    path('users/create/', views.user_create, name='user_create'),
    path('users/<int:pk>/update/', views.user_update, name='user_update'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),  
    path('slides/', views.slide_list, name='slide_list'),
    path('slides/create/', views.slide_create, name='slide_create'),
    path('slides/update/<int:pk>/', views.slide_update, name='slide_update'),
    path('slides/delete/<int:pk>/', views.slide_delete, name='slide_delete'),

    path('qris/', views.qris_list, name='qris_list'),
    path('qris/create/', views.qris_create, name='qris_create'),
    path('qris/<int:id>/update/', views.qris_update, name='qris_update'),
    path('qris/<int:id>/delete/', views.qris_delete, name='qris_delete'),
    path('update_status_pengembalian/<int:sewa_id>/', views.update_status_pengembalian, name='update_status_pengembalian'),
    path('', include('management.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/models.py
from django.db import models
from django.contrib.auth.models import User

from django.contrib.auth.models import AbstractUser

class Pelanggan(AbstractUser):
    nama = models.CharField(max_length=100, blank=True, null=True)
    alamat = models.CharField(max_length=200, blank=True, null=True)
    nomor_hp = models.CharField(max_length=20, blank=True, null=True)
    

    def __str__(self):
        return self.username

class Kategori(models.Model):
    nama = models.CharField(max_length=100)
    ddc = models.DecimalField(max_digits=10, decimal_places=2)
    def __str__(self):
        return self.nama


class Katalog(models.Model):
    kode = models.CharField(max_length=20)
    nama = models.CharField(max_length=100)
    gambar = models.ImageField(upload_to='media/gambar_katalog/')
    harga = models.PositiveIntegerField(blank=True, null=True)
    jumlah = models.IntegerField()
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)

class Sewa(models.Model):
    BELUM = 'Belum'
    SELESAI = 'Selesai'
    BELUM_SELESAI = 'Belum Selesai'
    PENDING = 'Pending'
    LUNAS = 'Lunas'
    DITOLAK = 'Ditolak'
    TIDAK = 'Tidak'
    BATAL = 'Batal'
    DI_ANTAR = 'Diantar'
    DI_AMBIL = 'Diambil'
    STATUS_CHOICES = [
        (BELUM, 'Belum'),
        (SELESAI, 'Selesai'),
        (BELUM_SELESAI, 'Belum Selesai'),
        (PENDING, 'Pending'),
        (LUNAS, 'Lunas'),
        (DITOLAK, 'Ditolak'),
    ]
    STATUS_CHOICESP = [
        (BELUM, 'Belum'),
        (SELESAI, 'Selesai')
      
    ]
    BATAL_CHOICES = [
        (TIDAK, 'Tidak'),
        (BATAL, 'Batal')
    ]
    TRANSFER = 'Transfer'
    BAYAR_DI_TEMPAT = 'Bayar di Tempat'
    JENIS_PEMBAYARAN_CHOICES = [
        (TRANSFER, 'Transfer'),
        (BAYAR_DI_TEMPAT, 'Bayar di Tempat'),
    ]
    METODE_PENGAMBILAN_CHOICES = [
        (DI_ANTAR, 'Diantar'),
        (DI_AMBIL, 'Diambil'),
    ]
    METODE_PENGEMBALIAN_CHOICES = [
        (DI_ANTAR, 'Diantar'),
        (DI_AMBIL, 'Diambil'),
    ]
    pelanggan = models.ForeignKey(Pelanggan, on_delete=models.CASCADE)
    tanggal_pakai = models.DateField()
    tanggal_ambil = models.DateField()
    tanggal_kembalikan = models.DateField()
    total_harga = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status_bayar = models.CharField(max_length=20, choices=STATUS_CHOICES, default=BELUM)
    status_pengembalian = models.CharField(max_length=20, choices=STATUS_CHOICESP, default=BELUM)
    jenis_pembayaran = models.CharField(max_length=20, choices=JENIS_PEMBAYARAN_CHOICES, default=TRANSFER)
    status_batalpesanan = models.CharField(max_length=20, choices=BATAL_CHOICES, default=TIDAK)
    metode_pengambilan = models.CharField(max_length=20, choices=METODE_PENGAMBILAN_CHOICES, default=DI_ANTAR)
    metode_pengembalian = models.CharField(max_length=20, choices=METODE_PENGEMBALIAN_CHOICES, default=DI_ANTAR)
    def total_harga(self):
        total = 0
        detail_sewa_list = self.detailsewa_set.all()
        for detail_sewa in detail_sewa_list:
            total += detail_sewa.jumlah * detail_sewa.katalog.harga * detail_sewa.jangkasewa
        return total

class DetailSewa(models.Model):
    sewa = models.ForeignKey(Sewa, on_delete=models.CASCADE)
    katalog = models.ForeignKey(Katalog, on_delete=models.CASCADE)
    jumlah = models.IntegerField()
    jangkasewa = models.IntegerField(null=True)
    @property
    def sub_total(self):
        return self.katalog.harga * self.jumlah * self.jangkasewa if self.katalog.harga and self.jumlah and self.jangkasewa else 0

class Slide(models.Model):
    gambar = models.ImageField(upload_to='media/slides/')
    keterangan = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.keterangan or "Slide tanpa keterangan"
    
class Qris(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.ImageField(upload_to='media/qris/')

    def __str__(self):
        return f"QRIS {self.id}"

class DetailPembayaran(models.Model):
    sewa = models.ForeignKey(Sewa, on_delete=models.CASCADE)
    bukti_file_pembayaran = models.ImageField(upload_to='media/detail_pembayaran/')

    def __str__(self):
        return f"Detail Pembayaran untuk Sewa ID {self.sewa.id}"

management/forms.py
from django import forms
from .models import Katalog,Kategori,User,Pelanggan,Sewa,DetailSewa,Slide,Qris,DetailPembayaran
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

class PelangganRegistrationForm(UserCreationForm):
    nama = forms.CharField(max_length=100, required=True)
    alamat = forms.CharField(max_length=200, required=True)
    nomor_hp = forms.CharField(max_length=20, required=True)

    class Meta:
        model = Pelanggan
        fields = ['nama', 'alamat', 'nomor_hp', 'username', 'email', 'password1', 'password2']
class KatalogForm(forms.ModelForm):
    class Meta:
        model = Katalog
        fields = ['kode', 'nama', 'gambar', 'harga', 'jumlah', 'kategori']

class KategoriForm(forms.ModelForm):
    class Meta:
        model = Kategori
        fields = ['nama', 'ddc']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class PelangganForm(forms.ModelForm):
    class Meta:
        model = Pelanggan
        fields = ['nama', 'alamat', 'nomor_hp']

class SewaForm(forms.ModelForm):
    class Meta:
        model = Sewa
        fields = ['pelanggan', 'tanggal_pakai', 'tanggal_ambil', 'tanggal_kembalikan']

class DetailSewaForm(forms.ModelForm):
    class Meta:
        model = DetailSewa
        fields = ['katalog', 'jumlah']

class SlideForm(forms.ModelForm):
    class Meta:
        model = Slide
        fields = ['gambar', 'keterangan']
        widgets = {
            'gambar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'keterangan': forms.TextInput(attrs={'class': 'form-control'}),
        }
class QrisForm(forms.ModelForm):
    class Meta:
        model = Qris
        fields = ['image']

class DetailPembayaranForm(forms.ModelForm):
    class Meta:
        model = DetailPembayaran
        fields = ['bukti_file_pembayaran']
DetailSewaFormSet = inlineformset_factory(Sewa, DetailSewa, form=DetailSewaForm, extra=1)

management/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sewa Baju{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        .carousel-image {
            height: 500px; /* Atur tinggi sesuai kebutuhan Anda */
            object-fit: cover; /* Menjaga rasio aspek dan memastikan gambar terpotong dengan baik jika terlalu besar */
        }

        .top-bar {
            background-color: #343a40;
            padding: 10px 0;
            border-bottom: 1px solid #dee2e6;
        }

        .top-bar .contact-info {
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: #ffffff;
        }

        .top-bar .contact-info .left,
        .top-bar .contact-info .right {
            font-size: 14px;
        }

        .navbar {
            background-color: #495057; /* Warna utama navbar */
        }

        .navbar-brand {
            color: #ffffff !important; /* Warna teks brand */
        }

        .navbar-nav .nav-link {
            color: #ffffff !important; /* Warna teks link */
            font-size: 0.85rem; /* Ukuran font lebih kecil */
        }

        .dropdown-menu {
            background-color: #6c757d; /* Warna background dropdown */
        }

        .dropdown-item {
            color: #ffffff !important; /* Warna teks dropdown item */
            font-size: 0.85rem; /* Ukuran font lebih kecil */
        }

        .footer {
            background-color: #343a40;
            color: #ffffff;
            padding: 20px 0;
        }

        .footer .text-muted {
            color: #868e96 !important;
        }

        /* Link hover */
        .navbar-nav .nav-link:hover, .dropdown-item:hover {
            color: #adb5bd !important;
        }

        /* Card hover effect */
        .card {
            transition: transform 0.2s;
        }

        .card:hover {
            transform: scale(1.05);
        }

        .card-img-top {
            height: 200px; /* Atur tinggi gambar sesuai kebutuhan */
            object-fit: cover; /* Menjaga rasio aspek dan memastikan gambar terpotong dengan baik jika terlalu besar */
        }
    </style>
    <style>
        #loading {
            position: fixed;
            z-index: 1000;
            height: 100%;
            width: 100%;
            overflow: hidden;
            margin: auto;
            top: 0;
            left: 0;
            background: rgba(255, 255, 255, 0.8);
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <header>
        <!-- Top bar for contact information -->
        <div class="top-bar">
            <div class="container">
                <div class="contact-info">
                    <div class="left">
                        <i class="fas fa-phone-alt"></i> +62 823-3490-5264
                    </div>
                    <div class="right">
                        <i class="fas fa-envelope"></i> contact@sewabaju.com
                    </div>
                </div>
            </div>
        </div>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'berandapelanggan' %}">Sewa Baju</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'berandapelanggan' %}"><i class="fas fa-home"></i> Beranda</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-th-list"></i> Kategori
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for kategori in kategori_list %}
                                    <a class="dropdown-item" href="{% url 'kategoripelanggan' kategori.id %}">{{ kategori.nama }}</a>
                                {% endfor %}
                            </div>
                        </li>
                        <!-- Menu tambahan -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'syarat_dan_ketentuan' %}">Syarat dan Ketentuan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cara_pemesanan' %}">Cara Pemesanan</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <form class="form-inline" method="get" action="{% url 'pencarianpelanggan' %}">
                                <input class="form-control mr-sm-2" type="search" placeholder="Cari DDC..." aria-label="Search" name="q">
                                <button class="btn btn-outline-light my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
                            </form>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'keranjangpelanggan' %}"><i class="fas fa-shopping-cart"></i> Keranjang</a>
                        </li>
                        
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'history_sewapelanggan' %}"><i class="fas fa-history"></i> Histori Sewa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logoutpelanggan' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                        </li>
                        {% else %}
                      
                        {% endif %}
                            {% comment %}  {% endcomment %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="loading" class="d-none">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <main role="main" class="container">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted">© 2023 Sewa Baju</span>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

management/templates/history_sewa.html
{% extends 'base.html' %} 
{% block title %}History Sewa{% endblock %} 
{% block content %} 
{% load humanize %}
<div class="container mt-4">
  <h2>History Sewa</h2>
  <!-- Display messages -->
  {% if messages %}
  <div class="alert-messages">
    {% for message in messages %}
    <div
      class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"
      role="alert"
    >
      {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr>
          <th>Tanggal Ambil</th>
          <th>Tanggal Pakai</th>
          <th>Tanggal Kembalikan</th>
          <th>Total Harga</th>
          <th>Status Bayar</th>
          <th>Status Pengembalian</th>
          <th>Jenis Pembayaran</th>
          <th>Aksi</th>
          <th>Status Pesanan</th>
          <th>Metode Pengambilan</th>
          <th>Status Pengembalian</th>
          <th>Denda</th>
        </tr>
      </thead>
      <tbody>
        {% for sewa in sewa_list %}
        <tr>
          <td>{{ sewa.tanggal_ambil }}</td>
          <td>{{ sewa.tanggal_pakai }}</td>
          <td>{{ sewa.tanggal_kembalikan }}</td>
          <td>Rp {{ sewa.total_harga|intcomma }}</td>
          <td>{{ sewa.get_status_bayar_display }}</td>
          <td>{{ sewa.get_status_pengembalian_display }}</td>
          <td>{{ sewa.jenis_pembayaran }}</td>
          <td>
            {% if sewa.status_bayar == 'Lunas' %}
            Anda Sudah Membayar
            {% else %}
            <button
                type="button"
                class="btn btn-info btn-sm bayar-button"
                data-id="{{ sewa.id }}"
                data-amount="{{ sewa.total_harga }}"
              >
                Bayar
              </button>
            {% endif %}
          </td>
          <td>
            {% if sewa.status_batalpesanan == 'Tidak' %}
            <button
              type="button"
              class="btn btn-danger btn-sm batal-button"
              data-id="{{ sewa.id }}"
              data-toggle="modal"
              data-target="#batalModal"
            >
              Batal
            </button>
            {% else %} {{sewa.status_batalpesanan}} {% endif %}
          </td>
          <td
            class="{% if sewa.metode_pengambilan == 'Warning' %}warning{% endif %}"
          >
            {% if sewa.metode_pengambilan == 'Warning' %}
            <i class="fas fa-exclamation-triangle custom-icon"></i> {{ sewa.metode_pengambilan }} 
            {% else %}
            <i class="fas fa-check default-icon"></i> {{ sewa.metode_pengambilan }}
            {% endif %}
          </td>
          <td
            class="{% if sewa.metode_pengembalian == 'Warning' %}warning{% endif %}"
          >
            {% if sewa.metode_pengembalian == 'Warning' %}
            <i class="fas fa-exclamation-triangle custom-icon"></i> {{ sewa.metode_pengembalian }}
            {% else %}
            <i class="fas fa-check default-icon"></i> {{ sewa.metode_pengembalian }}
            {% endif %}
          </td>
          <td>
            {% if sewa.status_pengembalian == 'Selesai' %} 0 {% else %} {{ sewa.denda|intcomma }} {% endif %}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="12">Belum ada data sewa.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- Modal untuk Pembatalan Pesanan -->
<div
  class="modal fade"
  id="batalModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="batalModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="batalModalLabel">
          Konfirmasi Pembatalan Pesanan
        </h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Apakah Anda yakin ingin membatalkan pesanan dengan ID:
        <span id="sewaIdBatal"></span>?
      </div>
      <div class="modal-footer">
        <form method="post" id="batalForm" action="{% url 'batal_sewa' %}">
          {% csrf_token %}
          <input type="hidden" id="sewa_id_batal" name="sewa_id" />
          <button type="submit" class="btn btn-danger">Batalkan Pesanan</button>
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Batal
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    var bayarButtons = document.querySelectorAll(".bayar-button");

    bayarButtons.forEach(function (button) {
      button.addEventListener("click", function () {
        var orderId = this.getAttribute("data-id");
        var grossAmount = this.getAttribute("data-amount");

        fetch("/generate_midtrans_token/", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
          },
          body: JSON.stringify({
            order_id: orderId,
            gross_amount: grossAmount,
          }),
        })
        .then((response) => response.json())
        .then((data) => {
          if (data.token) {
            window.open(
              `https://app.sandbox.midtrans.com/snap/v2/vtweb/${data.token}`,
              "_blank"
            );
          } else {
            alert("Failed to get token");
          }
        });
      });
    });
  });
</script>
{% endblock %}

management/templates/loginpelanggan.html
{% extends 'base.html' %}

{% block title %}Login Pelanggan{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Login Pelanggan</h2>
    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" id="id_username" name="username" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="id_password">Password:</label>
            <input type="password" id="id_password" name="password" class="form-control" required>
        </div>

        <!-- Tambahkan tautan "Lupa Password" -->
        <div class="form-group">
            <a href="https://api.whatsapp.com/send?phone=6282334905264&text=Lupa%20Password" target="_blank" class="btn btn-link">Lupa Password?</a>
        </div>
        
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

management/templates/registerpelanggan.html
{% extends 'base.html' %}

{% block title %}Registrasi Pelanggan{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Registrasi Pelanggan Baru</h2>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
                {% for field, errors in form.errors.items %}
                {% for error in errors %}
                <li>{{ field|title }}: {{ error }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% if messages %}
        <div class="alert alert-success">
            {{ messages }}
        </div>
        {% endif %}
        <div class="form-group">
            <label for="id_nama">Nama:</label>
            <input type="text" id="id_nama" name="nama" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="id_alamat">Alamat:</label>
            <input type="text" id="id_alamat" name="alamat" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="id_nomor_hp">Nomor hp:</label>
            <input type="text" id="id_nomor_hp" name="nomor_hp" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" id="id_username" name="username" class="form-control" required>
            <small id="usernameHelp" class="form-text text-muted">Wajib diisi. Maksimal 150 karakter. Hanya huruf, angka, dan @/./+/-/_ yang diperbolehkan.</small>
        </div>
        <div class="form-group">
            <label for="id_email">Alamat Email:</label>
            <input type="email" id="id_email" name="email" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="id_password1">Kata Sandi:</label>
            <input type="password" id="id_password1" name="password1" class="form-control" required>
            <small id="passwordHelp" class="form-text text-muted">
                Kata sandi harus terdiri dari minimal 8 karakter dan tidak boleh terlalu mirip dengan informasi pribadi Anda.
            </small>
        </div>
        <div class="form-group">
            <label for="id_password2">Konfirmasi Kata Sandi:</label>
            <input type="password" id="id_password2" name="password2" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Daftar</button>
    </form>
</div>
{% endblock %}